# Find NALU_HYPRE linear solver library
#
# Set NALU_HYPRE_DIR to the base directory where the package is installed
#
# Sets two variables
#   - NALU_HYPRE_INCLUDE_DIRS
#   - NALU_HYPRE_LIBRARIES
#

find_path(NALU_HYPRE_INCLUDE_DIRS
  NALU_HYPRE.h
  HINTS ${NALU_HYPRE_ROOT} ${NALU_HYPRE_DIR} ${CMAKE_INSTALL_PREFIX}
  PATH_SUFFIXES include)

find_library(NALU_HYPRE_LIBRARIES
  NAMES NALU_HYPRE NALU_HYPRE
  HINTS ${NALU_HYPRE_ROOT} ${NALU_HYPRE_DIR} ${CMAKE_INSTALL_PREFIX}
  PATH_SUFFIXES lib)

if (NALU_HYPRE_INCLUDE_DIRS)
  file(STRINGS ${NALU_HYPRE_INCLUDE_DIRS}/NALU_HYPRE_config.h
    _nalu_hypre_version_string REGEX "NALU_HYPRE_RELEASE_VERSION")
  string(REGEX MATCHALL "[0-9]+" NALU_HYPRE_VERSION "${_nalu_hypre_version_string}")
  string(REPLACE ";" "." NALU_HYPRE_VERSION "${NALU_HYPRE_VERSION}")
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  NALU_HYPRE DEFAULT_MSG NALU_HYPRE_VERSION NALU_HYPRE_INCLUDE_DIRS NALU_HYPRE_LIBRARIES)
mark_as_advanced(NALU_HYPRE_INCLUDE_DIRS NALU_HYPRE_LIBRARIES)

if (NALU_HYPRE_FOUND AND NOT TARGET NALU_HYPRE)
  add_library(NALU_HYPRE UNKNOWN IMPORTED GLOBAL)
  set_target_properties(NALU_HYPRE
    PROPERTIES
    IMPORTED_LOCATION "${NALU_HYPRE_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${NALU_HYPRE_INCLUDE_DIRS}")
endif()
